Models/Database/Entidades/Heroi.cs
namespace SuperHerois.Entidades;

public partial class Heroi
{
    public int Id { get; set; }
    public string Nome { get; set; } = null!;
    public string Poder { get; set; } = null!;
}

Models/Database/IMariaDbContext.cs
namespace SuperHerois.Models;

public interface IMariaDbContext
{
}

Models/Database/MariaDbContext.cs
using Microsoft.EntityFrameworkCore;
using SuperHerois.Entidades;

namespace SuperHerois.Models;

public partial class MariaDbContext : DbContext, IMariaDbContext
{
    private IConfiguration _config;

    public virtual DbSet<Heroi> Herois { get; set; } = null!;

    public MariaDbContext(IConfiguration config)        
    {
        _config = config;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseMySQL(_config.GetConnectionString("DefaultConnection"));
        }   
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Heroi>(entity =>
        {
            entity.ToTable("heroi");

            entity.Property(e => e.Id).HasColumnType("int(11)");

            entity.Property(e => e.Nome)
                .HasMaxLength(70)
                .HasDefaultValueSql(string.Empty);

            entity.Property(e => e.Poder)
                .HasMaxLength(70)
                .HasDefaultValueSql(string.Empty);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Models/ErrorViewModel.cs
namespace SuperHerois.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Repository/HeroiRepository.cs
using SuperHerois.Models.ViewModels;

namespace SuperHerois.Models.Repository;

public class HeroiRepository : IHeroiRepository
{
    private static int VALOR = 1;
    private List<HeroiViewModel> herois = new List<HeroiViewModel>();
    private IMariaDbContext _dbContext;

    public HeroiRepository(IMariaDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public List<HeroiViewModel> ObterTodosHerois() =>
        new List<HeroiViewModel>(herois);
    
    public HeroiViewModel? ObterHeroi(int id) =>
        herois.Where(h => h.Id == id).FirstOrDefault();
    
    public void AdicionarHeroi(HeroiViewModel heroi)
    {
        heroi.Id = VALOR++;
        herois.Add(heroi);
    }

    public void AtualizarHeroi(int id, HeroiViewModel heroi)
    {
        var index = herois.FindIndex(h => heroi.Id == id);
        herois[index] = heroi;
    }

    public void DeletarHeroi(int id) =>    
        herois.RemoveAll(h => h.Id == id);
}

Models/Repository/IHeroiRepository.cs
using SuperHerois.Models.ViewModels;

namespace SuperHerois.Models.Repository;

public interface IHeroiRepository
{
    public List<HeroiViewModel> ObterTodosHerois();
    public HeroiViewModel? ObterHeroi(int id);
    public void AdicionarHeroi(HeroiViewModel heroi);
    public void AtualizarHeroi(int id, HeroiViewModel heroi);
    public void DeletarHeroi(int id);
}

Models/ViewModels/ErrorViewModel.cs
namespace SuperHerois.Models.ViewModels;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/ViewModels/HeroiViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SuperHerois.Models.ViewModels
{
    public class HeroiViewModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Nome { get; set; }
        [Required]
        public string? Poder { get; set; }
    }
}

Controllers/MeusHeroisController.cs
using Microsoft.AspNetCore.Mvc;
using SuperHerois.Models.Repository;
using SuperHerois.Models.ViewModels;

namespace SuperHerois.Controllers
{
    public class MeusHeroisController : Controller
    {
        private IHeroiRepository _heroiRepository;

        public MeusHeroisController(IHeroiRepository heroiRepository)
        {
            _heroiRepository = heroiRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var herois = _heroiRepository.ObterTodosHerois();
            return View(herois);
        }

        [HttpGet]
        public IActionResult Detalhes(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }

            var heroi = _heroiRepository.ObterHeroi(id.GetValueOrDefault());
            if(heroi is null)
            {
                return NotFound();
            }

            return View(heroi);
        }

        [HttpGet]
        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Criar([Bind] HeroiViewModel heroi)
        {
            if(ModelState.IsValid)
            {
                _heroiRepository.AdicionarHeroi(heroi);
                return RedirectToAction("Detalhes", new { Id = heroi.Id });
            }

            return View(heroi);
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }

            var heroi = _heroiRepository.ObterHeroi(id.GetValueOrDefault());
            if (heroi is null)
            {
                return NotFound();
            }

            return View(heroi);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, [Bind] HeroiViewModel heroi)
        {
            if (id != heroi.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _heroiRepository.AtualizarHeroi(id, heroi);
                return RedirectToAction("Detalhes", new { Id = heroi.Id });
            }
            return View(heroi);
        }

        [HttpGet]
        public IActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var heroi = _heroiRepository.ObterHeroi(id.GetValueOrDefault());
            if (heroi is null)
            {
                return NotFound();
            }

            return View(heroi);
        }

        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmarDelete(int? id)
        {
            if(id is not null)
            {
                _heroiRepository.DeletarHeroi(id.GetValueOrDefault());
            }

            return RedirectToAction("Index");
        }
    }
}

Views/MeusHerois/Criar.cshtml
@model SuperHerois.Models.ViewModels.HeroiViewModel

@{
    ViewData["Title"] = "Criar Herói";
}

<h1>Criar seu Heroi</h1>

<h4>Adicione as características do seu Herói</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="MeusHerois" asp-action="Criar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poder" class="control-label"></label>
                <input asp-for="Poder" class="form-control" />
                <span asp-validation-for="Poder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar Meu Heroi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="MeusHerois" asp-action="Index">Back to List</a>
</div>

Views/MeusHerois/Deletar.cshtml
@model SuperHerois.Models.ViewModels.HeroiViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Deletar</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HeroiViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poder)
        </dd>
    </dl>
    
    <form asp-action="Deletar">
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar a lista</a>
    </form>
</div>
</body>
</html>

Views/MeusHerois/Detalhes.cshtml
@model SuperHerois.Models.ViewModels.HeroiViewModel
@{
    ViewData["Title"] = "Detalhes - Meus Herois";
}

<h1>Detalhe meu Herói</h1>

@if(Model is not null)
{
    <p>
        <strong>NUMERO #</strong>@Model?.Id
        <br />
        <strong>NOME:</strong> @Model?.Nome
        <br />
        <strong>PODER:</strong> @Model?.Poder
    </p>

    <a asp-controller="MeusHerois" asp-action="Editar" asp-route-id="@Model?.Id">Editar</a>
    <a asp-controller="MeusHerois" asp-action="Deletar" asp-route-id="@Model?.Id">Deletar</a>
}

Views/MeusHerois/Editar.cshtml
@model SuperHerois.Models.ViewModels.HeroiViewModel

@{
    ViewData["Title"] = "Editar - Meus Herois";
}

<h4>Editar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-controller="MeusHerois" asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poder" class="control-label"></label>
                <input asp-for="Poder" class="form-control" />
                <span asp-validation-for="Poder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar Herói" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar a Lista</a>
</div>

Views/MeusHerois/Index.cshtml
@model IEnumerable<SuperHerois.Models.ViewModels.HeroiViewModel>

@{
    ViewData["Title"] = "Meus Herois";
}

<h1>Olá meu Herói</h1>

<p>
    <a asp-action="Criar">Criar Novo Heroi</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poder)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Poder)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Editar", new { Id = item.Id }) |
                        @Html.ActionLink("Detalhes", "Detalhes", new { Id = item.Id }) |
                        @Html.ActionLink("Deletar", "Deletar", new { Id = item.Id })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperHerois</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SuperHerois.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="MeusHerois" asp-action="Index">SuperHerois</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MeusHerois" asp-action="Criar">Criar Heroi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MeusHerois" asp-action="Index">Ver Herois</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SuperHerois - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>